### ISSUE TITLE
pch.h can't to include

### ISSUE THREAD

**Issue by teris1994** [xarkes/L2Bot#8]
Hello i try compile but we can't include pch.h header.

**Comment by xarkes** [comment]
That's weird, I don't remember having a use for it, you should probably just remove it from the build.
Ref: https://learn.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=msvc-170

**Comment by teris1994** [comment]
Yes you have right !  For a reason he add the vs studio . Thank you for answer..
and thank you for this nice project!
